spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hoteldb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      platform: postgres
    data:
      platform: postgres
  liquibase:
    enabled: false  # Desativa o Liquibase para evitar conflitos com o Hibernate durante a inicialização

logging:
  level:
    org:
      hibernate:
        SQL: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Habilita todos os endpoints

  boot:
    admin:
      client:
        url: http://localhost:8080  # URL do servidor Spring Boot Admin
    application:
      name: hotel-api  # Nome da aplicação no Spring Boot Admin
