# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v3

    - name: Configurar o JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache das dependências do Gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-

    - name: Tornar o Gradlew Executável
      run: chmod +x gradlew

    - name: Build com o Gradle
      run: |
        ./gradlew build --warning-mode all
        
    - name: Executar os testes
      run: |
        ./gradlew test

    - name: Verificar a qualidade do código
      run: |
        ./gradlew check

    - name: Upload dos Resultados dos Testes
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: resultados-testes
        path: build/test-results

    - name: Upload do Relatório de Cobertura de Código
      if: always() && runner.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v2
      with:
        name: cobertura-codigo
        path: build/reports/jacoco/test/html
